<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<title>NIGHTOWL: Making it work for you: The Diynamic Camp</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="author" content="Rob Cary" />
<meta name="description" content="The internet home of DJ Nightowl" />

<link rel="stylesheet" href="/~rcary/cs148/finalproject/ss/NOdefault.css" type="text/css" title="nighttime" media="screen" />
<link rel="alternate stylesheet" href="/~rcary/cs148/finalproject/ss/NOdaytime.css" type="text/css" title="daytime" media="screen" />
<link rel="alternate stylesheet" href="/~rcary/cs148/finalproject/ss/NOtropical.css" type="text/css" title="tropical" media="screen" />
<link rel="alternate stylesheet" href="/~rcary/cs148/finalproject/ss/NOdarkness.css" type="text/css" title="darkness" media="screen" />

<script src="cookies.js" type="text/javascript"></script>

<script src="/~rcary/cs148/finalproject/styleCheck.js" type="text/javascript"></script>
</head>
<body>
<div style='float: right; top: 50%; text-align: right;'>
<h1>Making it work for you: The Diynamic Camp</h1>
</div>
<div style='float: left; width: 800px; height: 450px; overflow: auto; text-align: left;'>
<p style='text-indent: 2em;'>When your imprint rotates around three of the best German producers in the scene today, it is safe to say that your label can count on a series of solid releases, and this is absolutely true for Hamburg-based Diynamic Music, and in-house producers Mladen Solomun (Solomun), Holger Behn (H.O.S.H.), and Martin Stimming (Stimming). Records from these three, in addition to names like Kollektiv Turmstrasse, Isolee, and David August, have given Diynamic a rich, diverse library that includes a handful of excellent albums, many more excellent singles, and a wonderfully diverse remix series that brings on producers not associated with the label to remix the catalog.</p>
<p style='text-indent: 2em;'>The Diynamic sound, from this writer’s perspective, could be described as techno-leaning house with a focus on sound design, rhythm, and emotion. Perhaps the emotion is the most noticeable aspect of some Diynamic records, as the productions convincingly draw you in, trying to do with music what most songs try to do with lyrics. That emotion comes in the dynamics of the music and the melodies, which veer from catchy and unconcerned to going straight for the heart. Every Diynamic release is exciting, as you never really know what you’re going to get, but you know it’s going to sound great. That being said, let’s examine each of the three producers who have defined the Diynamic sound for over five years.</p>
<p style='text-indent: 2em;'>Let's start with Solomun, the quirkiest, pseudo-songwriter producer of the three. The German’s productions are always groovy, but it’s much more of a house vibe than a techno groove, which the other two producers of the three work a tad more. Solomun is perhaps the most radio-friendly of the three too, as some of his productions take a lot more from pop than usual, but his slick production always ensures that it will sound great, however the man experiments within the realm of house much more than Stimming or H.O.S.H. do.</p>
<p style='text-indent: 2em;'>Take, for example, “After Rain Comes Sun”, off of Solomun’s “Dance Baby” LP. The track employs very trancey synths in a much slower manner, giving the track its moody, lush foundation on which the strings that soon follow fit perfectly. With a soft and subtle house shuffle, we’re treated to a melancholic house gem that rolls along with a dramatic, swelling groove. On the fourth edition of Remix: Sessions, Joris Voorn was brought on to do a remix that nips the melancholy in the nail and stretches the drama out, even managing to draw a kind of intimacy out of the original. There is no question that the remix is groovier, as it risks more on account of Voorn’s more-repetitive-than-usual drum patterns. However, it is immediately saved by Voorn’s expert sense of pacing and tension, plus it's useless even to call his drum patterns repetitive, as they are the rhythmic foundation to his groove, and no one does hi-hats better than Joris Voorn.</p>
<p style='text-indent: 2em;'>Solomun shows his true house colors with “Cloud Dancer”, another cut form his album. A fantastically rhythmic intro leads into a drum-heavy, bass-supple groove. The vocal, courtesy of vocalist Ole Soul, rides the groove beautifully, wringing the funk and soul out of the track, once again demonstrating Solomun’s versatility as a producer. The fifth edition of Remix: Sessions features a masterful deep house reworking by Manuel Tur which turns up the drama, turns up the groove, and turns up the sexy! The intro alone ratchets the drama up! The ominous bass hums under the sheets of percussion make the vocal the dark, slightly creepy faceless thing that gets its fire back the minute the groove kicks in. An impressive, nearly eight minute re-imagining of a great original.</p>
<p style='text-indent: 2em;'>The final Solomun track I’d like to look at comes from the four-way split “Four Seasons” EP. Solomun’s cut, “Second Kiss In Winter” sees him losing none of his quirkiness, as the main synth line feels decidedly mystical and almost video-game inspired, though it’s no less hypnotic and catchy for it. Deep bass stabs sustain the groove underneath the skittish, brittle-sounding percussion, which acts as a nice foil to the gooeyness of the synths. A beautiful track that shows yet another side of Solomun, that of a deeper techno variety. Solomun is a good jumping-off point for those with a sense of humor in their music, a more diverse sound palette, and a wealth of releases on a variety of different labels.</p>
<p style='text-indent: 2em;'>Holger Behn, known as H.O.S.H. in the production world, as a handful of releases to his name, less than Solomun and mostly on Diynamic. However, his developing sound is rather curious, for it features weird melodies and unusual rhythmic patterns that sets it apart from most other producers around him. H.O.S.H.’s productions are easily the deepest of the three. I feel like there’s a better way to say that...his productions feel the most expansive, and employ musical techniques to give them an unprecedented amount of weight in their sound, especially in the low end.</p>
<p style='text-indent: 2em;'>"Souled Out” is a great production to start with. Off his debut album on Diynamic, “Connecting.The.Dots”, features a bass-heavy hum that permeates the whole track and gives it a powerful sense of anxiety, urgency, and objective. This track maintains an unrelenting groove thanks to the weight of the piano and the pop and snap of the drums. A great work of drama that never goes overboard and plays to its strengths. One of H.O.S.H.’s best works comes from his “Under A Fig Tree” EP, the wickedly groovy “Super Sick Bowl”. The push and pull of this track is especially noteworthy here; the emphasis H.O.S.H. places on certain notes and sounds and when he places it there gives the track a real notion of ebb and flow, resulting in an immediately catchy groove that’s rock-solid and expert in its sense of tension and release. Behn turns over a jazzy new leaf in this, the last of his cuts I’m going to look at. “Jazzkantine” features an organ, an instrument often found in the folds of the Diynamic catalog, a rolling tech house groove, and a great vocal line that builds anticipation and drama for the ride ahead. Those who love to dance would do best to look into more H.O.S.H. releases, it is his strongest suit, thanks to his unusual rhythms and great feel for tension and release in a groove.</p>
<p style='text-indent: 2em;'>Finally, we come to Stimming. Like Solomun, Stimming has been around a while, and has released on a great many labels, from his usual home at Diynamic, Green, Audiomatique, and liebe*detail, to dirtybird, Buzzin’ Fly, Systematic, and Great Stuff. His is probably my favorite of the three, although I have grown to appreciate Solomun a great deal more than a used to, plus Stimming’s sound seems to have slimmed up and slowed down, which I have not really found favor with. Needless to say, there are plenty of older Stimming tracks worthy of at least one listen. “Madleine” helmed the A-side of an EP Stimming did for Diynamic with fellow German producer Einmusik, and the results were stellar. A powerful, sensuous basslines rubs up against Stimming’s typical wooden rhythms and his usual percussive pop. The drama is high here, but it’s handled expertly, never getting out of control or boring in the slightest. Great synth work and even better atmosphere.</p>
<p style='text-indent: 2em;'>"Una Pena” is notable for its sound design, which features the use of the now-trademark Stimming ’boat-keel’, a percussive element that sound not unlike the creaking of ship moving briskly through the water. Stimming’s cavernous, lumbering wooden percussion is on full display in this cut, and it’s a marvel just to listen to. The track literally creaks, sputters, and hums, like it’s some kind of living, breathing entity. At the drop of the vocal, the groove unfolds fully, an idiosyncratic shuffle with bells and the stiff crackle of Stimming’s snares. Argy gives the track a tribal reworking, smudging the atmosphere up, employing lush, otherworldly synths and definitively turning the groove from day to night. Just as dancefloor-ready as it is headphones ready.</p>
<p style='text-indent: 2em;'>One of Stimming’s earlier releases, “Funkworm” EP’s title track features some Stimming’s grooviest, funkiest material. Centering around a neat little guitar riff, the atmosphere is heavy with creaks, reverb, and low horn blurts. The groove burns to life all of a suddenly shortly there after, and just like that, Stimming gets down to business, building a supple groove that hums with energy. The plink of the synths juxtapose the busy low-end nicely, and the whole affair delivers quite the ride in just over eight minutes.</p>
<p style='text-indent: 2em;'>This is only a sample of the great releases in the Diynamic catalog, and as a jumping off point, here are some other releases to look into:</p>
	<ul>
		<li style='list-style-type:square;'><a href="/~rcary/cs148/finalproject/browse/releasePage.php?CatNum=DIYNAMIC 029">iO / Cabaret EP</a></li>
		<li style='list-style-type:square;'><a href="/~rcary/cs148/finalproject/browse/releasePage.php?CatNum=DIYNAMIC 032">Kollektiv Turmstrasse / Like The First Day</a></li>
		<li style='list-style-type:square;'><a href="/~rcary/cs148/finalproject/browse/releasePage.php?CatNum=DIYNAMIC 038">Ost and Kjex / Remix: Session 06</a></li>
	</ul>
<p>Enjoy, folks. ~Nightowl</p>
</div>
<?php include("menubar.php"); ?>
</body>
</html>